---
title: "PS-GC-LN-06-1-Raster-Vector calculations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
require(knitr)
opts_knit$set(root.dir = '/home/hanna/Documents/Lehre/2016/Projektseminar/Excercises/session05/')
```

### Load libraries und set data path
```{r message=FALSE}
library(rgdal)
library(raster)

setwd("/home/hanna/Documents/Lehre/2016/Projektseminar/Excercises/session05/")

```


### Calculate the average yearly temperatures
```{r}
files <- list.files("tmean_deu",pattern=".tif$",full.names=T)
yeart <- stack(files) #stack the indivisual files
yeart <- yeart/10 #divide all by 10
yearly_mean <- calc(yeart,mean) #calculate the average

```

### Extract values: Use the mean of each state
```{r}
lyr <- ogrListLayers("DEU_adm1.shp")[1]
gadm <- readOGR("DEU_adm1.shp",layer=lyr)
tmean_extraction <- extract(yearly_mean,fun=mean,gadm,df=TRUE)
tmean_extraction_sd <- extract(yearly_mean,fun=sd,gadm,df=TRUE)
#rename columns (from "layer"" to more useful names)
names(tmean_extraction)[2] <- "mean"
names(tmean_extraction_sd)[2] <- "sd"

```
attach the new data to the attributes of gadm
```{r}
###Version 1: MERGE
head(gadm@data) # see attribute table
result <- merge(gadm,tmean_extraction,by.x="ID_1",by.y="ID")
#merge result with sd
result <- merge(result,tmean_extraction_sd,by.x="ID_1",by.y="ID")
head(result@data)
###Version 2: Add extraction directly to attribute table
#gadm@data$mean <- tmean_extraction$mean
#gadm@data$sd <- tmean_extraction_sd$sd

### Plot results
spplot(result,zcol = c("mean","sd"))
```
