---
title: "PS-GC-LN-06-Raster-Vector calculations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
require(knitr)
opts_knit$set(root.dir = '/home/hanna/Documents/Lehre/2016/Projektseminar/Excercises/session05/')
```

### Load libraries und set data path
```{r message=FALSE}
library(rgdal)
library(raster)

setwd("/home/hanna/Documents/Lehre/2016/Projektseminar/Excercises/session05/")

```


### 1) Calculate the average yearly temperatures
```{r}
files <- list.files("tmean_deu",pattern=".tif$",full.names=T)
yeart <- stack(files) #stack the indivisual files
yeart <- yeart/10 #divide all by 10
yearly_mean <- calc(yeart,mean) #calculate the average

```

### 2) Extract values: Use the mean of each state
```{r}
lyr <- ogrListLayers("DEU_adm1.shp")[1]
gadm <- readOGR("DEU_adm1.shp",layer=lyr)
tmean_extraction <- extract(yearly_mean,fun=mean,gadm,df=TRUE)
tmean_extraction_sd <- extract(yearly_mean,fun=sd,gadm,df=TRUE)
```
attach the new data to the attributes of gadm
```{r}
gadm@data <- data.frame(gadm@data,"mean" = tmean_extraction$layer,
                        "sd"=tmean_extraction_sd$layer)
spplot(gadm,zcol = c("mean","sd"))
```

### 2) Normalize data
For raster data:
```{r}
#use the stretch function
yearly_mean_norm_V1 <- stretch(yearly_mean,0,1)
#or use formula (x-min)/(max-min)
yearly_mean_norm_V2 <-  (yearly_mean- cellStats(yearly_mean,min))/(cellStats(yearly_mean,max) - cellStats(yearly_mean,min))
#or use scale with center is the min values and scale is the difference between max and min
yearly_mean_norm_V3 <- scale(yearly_mean, center = cellStats(yearly_mean,min), scale = cellStats(yearly_mean,max) - cellStats(yearly_mean,min))

```

Scaling vector data works in the same way 8except for that the easy function
"stretch" is not working because this is a function for raster data only.
```{r}
#use formula (x-min)/(max-min)
gadm_norm_V1 <-  (gadm@data$mean- min(gadm@data$mean))/(max(gadm@data$mean) - min(gadm@data$mean))
#or using scale function
gadm_norm_V2 <- scale(gadm@data$mean, center = min(gadm@data$mean), scale = max(gadm@data$mean) - min(gadm@data$mean))
#or a function from clusterSim package
library(clusterSim)
gadm_norm_V3 <- data.Normalization(gadm@data$mean,type="n4")

library(scales)
gadm_norm_V4 <- rescale(gadm@data$mean, to = c(0, 1))

#check if they are identical:
identical(gadm_norm_V4,gadm_norm_V1)
```